### PR TITLE
Add an option 'ENABLE_MAINLINE_QTXDG' to use mainline libqtxdg

### PR DESCRIPTION
**Pull request by schnitzeltony**
Signed-off-by: Andreas Müller <schnitzeltony@googlemail.com>

### CODE REVIEW

**Comment by schnitzeltony** [comment]
OOps - I did it again this went out too early - Linker complaints. V2 will come fully tested soon - promised...

**Comment by plfiorini** [comment]
Take your time :)

**Comment by schnitzeltony** [comment]
V1 -> V2:
* add HawaiiQtXDG -> qtxdg to session also
* fix build for HawaiiQtXDG - this was necessary to test ENABLE_MAINLINE_QTXDG ON/OFF

**Comment by plfiorini** [comment]
Merged.

**Pull request closed without merging**
